serviceName: "frontend"
replicaCount: 1

service:
  enabled: true
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 5173

env:
  - name: PORT
    value: "5173"
  - name: VITE_API_BASE_URL
    value: "https://exp-service-backend.runnto.com/api"

livenessProbe: {}
readinessProbe: {}
startupProbe: {}
persistence: {}
resources: {}
envFromConfigMap: {}
