serviceName: "backend"
replicaCount: 1

service:
  enabled: true
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3000

env:
  - name: LOG_LEVEL
    value: "info"
  - name: PORT
    value: "3000"
  - name: NODE_ENV
    value: "development"
  - name: DATA_SOURCE
    value: "mock"
  - name: KUaidi100_KEY
    value: "byrAGPwv7930"
  - name: KUaidi100_CUSTOMER
    value: "1E99013A55CB29192A9C91BD14998EC9"
  - name: KUaidi100_SECRET
    value: "6c2bb72b6a1b4a04bd29a9bf8f110c05"
  - name: APP_BASE_URL
    value: "http://exp-service-backend.runnto.com"

livenessProbe: {}
readinessProbe: {}
startupProbe: {}
persistence: {}
resources: {}
envFromConfigMap: {}
