module.exports = {
  ERROR_CODES: {
    SUCCESS: 200,
    BAD_REQUEST: 400,
    NOT_FOUND: 404,
    RATE_LIMIT: 429,
    SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503
  },
  
  CRAWLER_ERRORS: {
    TIMEOUT: 'TIMEOUT',
    NETWORK_ERROR: 'NETWORK_ERROR',
    PARSE_ERROR: 'PARSE_ERROR',
    BLOCKED: 'BLOCKED',
    UNKNOWN: 'UNKNOWN'
  }
}
